### PR TITLE
Yuji - Dropdown for DriverID in create shifts

### LINKED ISSUE #12: FEATURE: Change Driver Id text fields to dropdown
# User Story

*  As an Admin
* I can select a driver from a dropdown
* So that I dont have to memorize driver ids

### Discussion

Right now, when admins are creating shifts, the form contain text boxes where the admin has to input the `Driver Id`.

image

This is inconvenient because, the admin either has to memorize witch driver id corresponds to which person, check it beforehand, or if they don't remember while filling out the form, they have to check and potentially lose progress.

It would be much easier to be able to select from a dropdown list that contains all of the active driver ids and their names.

### Acceptance Criteria

- [ ] When creating shifts, an admin can select the `Driver ID` and `Backup Driver ID` from a dropdown containing all of the drivers

### Implementation Todos

Frontend:
- [ ] Modify `ShiftForm.js` to use the backend `DriversController.java` get all endpoint to get a list of all drivers and use it to populate a dropdown.

### PR DESCRIPTION
**Pull request by yuji-sakaguchi**
### Issue to fix
Currently have to manually check and search for Driver ID's when creating a new shift as admin.

### Changes for Create Shift
Added a dropdown for DriverID and Backup Driver ID in create shifts so an admin can easily select from a dropdown containing all of the drivers.
Added a "Select a driver" placeholder for the dropdown.
Changed Form.Control to Form.Select to appropriately handle dropdown menu options.
Added useBackend in shiftForm, and changed ShiftForm, ShiftEditPage, ShiftCreatePage tests.
Ensured that the admin user is not automatically assigned as the primary driver in ShiftController.java. 
No need to manually check and search for Driver ID's now. Dropdown will give all existing Driver ID's.

Dokku Deployment: https://proj-gauchoride-yuji-sakaguchi-dev.dokku-14.cs.ucsb.edu/

Please also review https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-6/pull/47 since I found additional bugs

Closes #12 

image

### CODE REVIEW

**Review by amisra0 — DISMISSED** [review]
LGTM, I tested and there is a dropdown for all drivers in drivers and backup drivers that lists their id. Creating a shift works successfully, the info, edit, and delete all still works so the code seems to be working as intended.

**Comment by pconrad** [comment]
See discussion on team slack channel.. I think I found a few bugs with the current deployment.
https://ucsb-cs156-s24.slack.com/archives/C06RGNALUES/p1716689298745709

**Review by jeffsmithepic — DISMISSED** [review]
LGTM; dropdown bug and admins being able to pick a driver is resolved.

One small issue; users can create new shifts where the `Shift End` is of an earlier date than the `Shift Start`- should this be resolved in a separate issue?

**Review by andrewpengucsb — APPROVED** [review]
LGTM

**Review by amisra0 — APPROVED** [review]
LGTM, I see the dropdown and the shift is properly created on Dokku instance.

**Pull request merged**
