### PR TITLE
Lindsey - Automatically toggle rider role after accepting application feature

### LINKED ISSUE #4: FEATURE: Accepting a rider application should modify the user's role
### As a...

admin

### I can...

accept rider applications that will automatically assign the user to be a rider

### So that...

I dont have to manually change their roles in the user table

### Discussion

Right now, when a ride application is accepted, only the status of the ride application is changed. So the admin has to go to the table of users and find the user who submitted the application and manually toggle their role.

What is better is, if the application is accepted, then the user who submitted the application gains the role automatically.

### Acceptance Criteria

- [ ] When an admin accepts a rider application through the review form, the user gains the `Rider` role.

### Implementation Todos

Frontend:
- [ ] In `RiderApplicationEditForm.js` modify the `handleApprove` method to include toggling of the applicant's role. You can look at `UsersTable.js` to see how it is done there and adapt appropriately.

### PR DESCRIPTION
**Pull request by lindseywn**
- Added function to automatically toggle a member's rider role after their application has been accepted 
- Added test as well, passing npm test and stryker
- Deployment link: https://project-lindseywn.dokku-14.cs.ucsb.edu/
- Make sure to use @ucsb.edu emails when using the deployment link. Alternatively, if no way of using ucsb emails, can test locally by temporarily changing SecurityConfig to include @gmail.com emails.
- Currently, you will not be able to see rider applications that are created from a different account. This is due to a bug in the existing code but I've fixed it in https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-6/pull/40
- Steps to test the automatically toggling feature:
1. Using your UCSB email with admin role as true and rider role as false, click Apply to be a Rider and create an application.
2. Go to Rider Applications and approve your own application.
3. Go to Users table and see that rider role is now true.

Before accepting application (lindseywen@ucsb.edu rider role is false)
Screen Shot 2024-05-21 at 10 05 04 PM

Application created (status: pending)
Screen Shot 2024-05-21 at 10 05 53 PM

Application accepted (status: accepted)
Screen Shot 2024-05-21 at 10 06 43 PM

After application accepted, lindseywen@ucsb.edu rider role is now true
Screen Shot 2024-05-21 at 10 07 15 PM

Closes #4

### CODE REVIEW

**Review by lizzyinnie — DISMISSED** [review]
lgtm! tested locally and it works as expected.

**Review by lizzyinnie — APPROVED** [review]
lgtm! tested locally and it works as expected.

**Comment by pconrad** [comment]
@lindseywn I tried testing this.   I created a user that had no roles: neither admin, nor driver, nor

**Comment by pconrad** [comment]
I was unable to get through the scenario for testing this.   I had trouble approving a rider application as an admin.

This is what I saw:

cannot-get-rider-application

**Review by pconrad — APPROVED** [review]
LGTM

**Pull request merged**
