### PR TITLE
Diya new driver index page

### LINKED ISSUE #5: FEATURE: Improve the usability of the admin DriverAvailabiltyIndexPage
### As a...

Admin

### I can...

know whos availability each row in the table is

### So that...

its easier to view quickly

### Discussion

image

Admins can view every `DriverAvailability` submitted by any driver by clickling `Driver Availabilities` under the `Admin` dropdown on the navbar. But right now each entry in the table, simply shows just the driver id. 

In other place in the application, the driver id is a hyperlink that takes the user to a information page on that driver. For this table, we want to do the same and have the driverId be a hyperlink to the information page like on the `Shifts` page. 

The second thing regarding this index page is the review button. It doesn't do anything and there is no purpose for it being there. Please remove it.

### Acceptance Criteria

- [x] Admin can click on the Driver Id and it will take them to the same information page that you get from the Shifts page.
- [x] `Review` button is removed

### Implementation Todos

Frontend:
- [x] Modify `DriverAvailabilityTable.js` to fulfill acceptance critera. Use `ShiftTable.js` as an example.
- [x] Remove the `Review` button from `DriverAvailabilityTable.js`

### PR DESCRIPTION
**Pull request by diyaparm**
Made it so when you click on the driver id in DriverAvailabiltyIndexPage it takes you to the driver info page. Removed the return button from this page and made sure that all tests are passing for all driver pages. 

See how Driver id is a link now:
Screenshot 2024-05-21 at 6 14 28 PM

Link takes you to this page (return takes you back):
Screenshot 2024-05-21 at 6 15 01 PM

Closes #5

### CODE REVIEW

**Review by jeffsmithepic — DISMISSED** [review]
LGTM; tests pass and works properly on frontend for non-drivers and drivers

**Review by andrewpengucsb — CHANGES_REQUESTED** [review]
Please revert any changes to `package-lock.json`.

Rest of the PR content looks good though.

**Review by lindseywn — APPROVED** [review]
LGTM, package lock reverted

**Review by andrewpengucsb — APPROVED** [review]
LGTM

**Pull request merged**
